### ISSUE TITLE
Cannot register key with integer value as the default for one with double value

### ISSUE THREAD

**Issue by Meronat** [LanternPowered/LanternServer#17]
![image](https://user-images.githubusercontent.com/18372958/27633395-a1ac56c0-5bc4-11e7-8abb-fad4634e7010.png)

**Comment by Cybermaxke** [comment]
You cannot pass another key as the default value, like you did here. And I added methods with `Function`s to use maximum and minimum values of different types.
For example:
`
        c.registerWithSuppliedMax(LanternKeys.MAX_SATURATION, 40.0, 0.0,
                container -> container.get(Keys.FOOD_LEVEL).get().doubleValue());`

**Comment by Meronat** [comment]
Thank you very much :)
