### ISSUE TITLE
Gradle generates wrapper on every import it seems

### ISSUE THREAD

**Issue by Meronat** [LanternPowered/LanternServer#18]
This makes me have to remove the wrapper changes from my commits as it causes unnecessary changes and slows down import times. Would be best to make the wrapper task run only on demand for when we truly want to update it. 

You can see this how in a lot of your commits, the wrapper dates change.

**Comment by Cybermaxke** [comment]
This is because of intellij, I think. When you reimport the project.

**Comment by Meronat** [comment]
It doesn't happen to my other projects which use the wrapper task I think. I'll look into the differences to see why this is occurring.

**Comment by Cybermaxke** [comment]
With reimport, I mean removing the .idea config folder and opening the gradle project again. I don't like to do it, but sometimes crashes my laptop and intellij isn't crash proof.

**Comment by Meronat** [comment]
Sweet thanks :>
