### ISSUE TITLE
Plugin/injection mistakes

### ISSUE THREAD

**Issue by Cybermaxke** [LanternPowered/LanternServer#26]
You can easily make some mistakes when making a plugin and using injection. It would nice if we could catch these issues prematurely, the same could be done for sponge. A few examples:

- ~~Using `java.util.logging.Logger` instead of `org.slf4j.Logger` (`org.apache.logging.log4j.Logger` could also work, but is not available in the standard sponge api environment)~~ https://github.com/minecraft-dev/MinecraftDev/issues/361
- ~~Using wrong `Named` annotations with injection.~~ The `org.spongepowered.api.event.filter.cause.Named` annotation got removed.
  - ~~`com.google.inject.name.Named` - YES~~
  - ~~`javax.inject.Named` - YES~~
  - ~~`org.spongepowered.api.event.filter.cause.Named` - NO~~
- ~~Missing `@Listener` on listener methods. Could be warned about by checking if the method is never called and has a valid listener signature.~~ MinecraftDev marks event methods as used/unused if a event method is/isn't annotated.
- ...

~~A annotation processor could help warn about these issues at compile time.~~
[MinecraftDev](https://github.com/minecraft-dev/MinecraftDev) supports a lot of features that help with these problems so it's recommend to use that plugin.

**Comment by kinggoesgaming** [comment]
Annotation processing is my kinda thing I will see to it

**Comment by kinggoesgaming** [comment]
As it stands, everything but the `@Listener` checks should be easy to handle with annotation processing.

The reason I can't use AP for Listeners is that an annotation processor only triggers if it detects a supporting annotation and not the other way round (aka missing annotation). We might have to look for other ways for that.

**Comment by Cybermaxke** [comment]
@kinggoesgaming I can try to create a class transformer, that could be run at runtime or maybe in a gradle task. I am not sure how the gradle task would work, but you can transform classes with the shadow plugin.

**Comment by Cybermaxke** [comment]
All the possible mistakes got resolved.
