### ISSUE TITLE
Nucleus causes errors on some of its event listener registration

### ISSUE THREAD

**Issue by Meronat** [LanternPowered/LanternServer#30]
I am not sure where this problem sprouts from or if it is even problematic, but it does spit out quite a few errors to the console. I couldn't really follow the stacktrace well into what is occurring in Nucleus.

https://gist.github.com/Meronat/10afccb29517684afcdc8ed38f7b2ae5

**Comment by Meronat** [comment]
@dualspiral may have some input here.

**Comment by dualspiral** [comment]
When did it crash? Startup or reload?

**Comment by Meronat** [comment]
@dualspiral So it does not crash, Lantern and Nucleus both continue to work. This is on start-up though as Nucleus is registering its listeners initially. 

It seems Nucleus may be registering these listeners more than once somehow or Lantern may be doing something wrong. See the registration code:

https://github.com/LanternPowered/LanternServer/blob/master/src/main/java/org/lanternpowered/server/event/LanternEventManager.java#L172

**Comment by dualspiral** [comment]
If anything, it's unregistrstion that's the problem - it may not be unregistering.
